/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as RepositoriesOwnerRepoRouteImport } from './routes/repositories.$owner.$repo'

const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const RepositoriesOwnerRepoRoute = RepositoriesOwnerRepoRouteImport.update({
  id: '/$owner/$repo',
  path: '/$owner/$repo',
  getParentRoute: () => RepositoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports': typeof ReportsRouteWithChildren
  '/repositories': typeof RepositoriesRouteWithChildren
  '/reports/$id': typeof ReportsIdRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/radar'
    | '/reports'
    | '/repositories'
    | '/reports/$id'
    | '/repositories/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/radar'
    | '/reports'
    | '/repositories'
    | '/reports/$id'
    | '/repositories/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/radar'
    | '/reports'
    | '/repositories'
    | '/reports/$id'
    | '/repositories/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  RadarRoute: typeof RadarRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RepositoriesRoute: typeof RepositoriesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/repositories/$owner/$repo': {
      id: '/repositories/$owner/$repo'
      path: '/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof RepositoriesOwnerRepoRouteImport
      parentRoute: typeof RepositoriesRoute
    }
  }
}

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface RepositoriesRouteChildren {
  RepositoriesOwnerRepoRoute: typeof RepositoriesOwnerRepoRoute
}

const RepositoriesRouteChildren: RepositoriesRouteChildren = {
  RepositoriesOwnerRepoRoute: RepositoriesOwnerRepoRoute,
}

const RepositoriesRouteWithChildren = RepositoriesRoute._addFileChildren(
  RepositoriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  RadarRoute: RadarRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RepositoriesRoute: RepositoriesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
