/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as RepositoriesOwnerRepoRouteImport } from './routes/repositories.$owner.$repo'

const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesOwnerRepoRoute = RepositoriesOwnerRepoRouteImport.update({
  id: '/repositories/$owner/$repo',
  path: '/repositories/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports': typeof ReportsIndexRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/radar': typeof RadarRoute
  '/reports/$id': typeof ReportsIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/repositories/$owner/$repo': typeof RepositoriesOwnerRepoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/radar'
    | '/reports/$id'
    | '/reports/'
    | '/repositories/'
    | '/repositories/$owner/$repo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/radar'
    | '/reports/$id'
    | '/reports'
    | '/repositories'
    | '/repositories/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/radar'
    | '/reports/$id'
    | '/reports/'
    | '/repositories/'
    | '/repositories/$owner/$repo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  RadarRoute: typeof RadarRoute
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  RepositoriesOwnerRepoRoute: typeof RepositoriesOwnerRepoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$owner/$repo': {
      id: '/repositories/$owner/$repo'
      path: '/repositories/$owner/$repo'
      fullPath: '/repositories/$owner/$repo'
      preLoaderRoute: typeof RepositoriesOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  RadarRoute: RadarRoute,
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  RepositoriesOwnerRepoRoute: RepositoriesOwnerRepoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
