# Frontend Dockerfile
FROM node:22-alpine

WORKDIR /app

# Install all dependencies
COPY package*.json ./
RUN npm ci --legacy-peer-deps

# Copy source code
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000" ]