import { createFileRoute, Link } from "@tanstack/react-router";
import { Sparkles, ArrowLeft, Download, Share2 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { useReport } from "@/hooks/use-reports";

export const Route = createFileRoute("/reports/$id")({
  head: ({ params }) => ({
    meta: [
      { title: `Report #${params.id} — OpenSource Pulse` },
      { name: "description", content: "Full AI-generated weekly intelligence report." },
    ],
  }),
  component: ReportDetail,
});

function ReportDetail() {
  const { id } = Route.useParams();
  const { data: report, isLoading } = useReport(Number(id));

  if (isLoading) {
    return (
      <>
        <PageHeader title="Loading..." description="" />
        <div className="p-8 text-center text-muted-foreground text-sm font-mono">Loading report...</div>
      </>
    );
  }

  if (!report) {
    return (
      <>
        <PageHeader title="Report Not Found" description="" />
        <div className="p-8 text-center text-muted-foreground text-sm font-mono">
          Report not found.
          <Link to="/reports" className="block mt-4 text-accent hover:underline">Back to reports</Link>
        </div>
      </>
    );
  }

  const content = report.report_content || "No content available for this report.";

  return (
    <>
      <PageHeader
        title={report.title}
        description={`Published ${new Date(report.generated_at).toLocaleDateString()} · Generated by Pulse AI`}
        actions={
          <div className="flex gap-2">
            <button className="h-8 inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-3 text-xs text-muted-foreground hover:text-foreground">
              <Download className="h-3.5 w-3.5" /> Export
            </button>
            <button className="h-8 inline-flex items-center gap-1.5 rounded-md border border-border bg-card px-3 text-xs text-muted-foreground hover:text-foreground">
              <Share2 className="h-3.5 w-3.5" /> Share
            </button>
          </div>
        }
      />

      <div className="px-4 md:px-8 py-8">
        <Link to="/reports" className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground mb-6">
          <ArrowLeft className="h-3 w-3" /> All reports
        </Link>

        <article className="mx-auto max-w-3xl space-y-10">
          <section>
            <div className="flex items-center gap-2 text-xs uppercase tracking-wider text-accent">
              <Sparkles className="h-3.5 w-3.5" /> Report
            </div>
            <div className="mt-3 text-base leading-relaxed text-foreground/90 whitespace-pre-wrap">
              {content}
            </div>
          </section>
        </article>
      </div>
    </>
  );
}
